SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `user` 
DROP FOREIGN KEY `fk_user_base1`;

ALTER TABLE `user` 
DROP COLUMN `main_base_id`,
DROP INDEX `fk_user_base1_idx` ,
DROP INDEX `main_base_id_UNIQUE` ;

ALTER TABLE `base` 
ADD COLUMN `created_at` INT(11) NOT NULL AFTER `produced_water`,
ADD COLUMN `updated_at` INT(11) NOT NULL AFTER `created_at`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
